name: intelligent-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.1.1
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - annotated-types=0.6.0
  - anyio=4.2.0
  - aom=3.9.1
  - async-timeout=4.0.3
  - attrs=23.1.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cairo=1.18.0
  - certifi=2024.7.4
  - charset-normalizer=3.3.2
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - contourpy=1.2.0
  - cycler=0.11.0
  - dav1d=1.2.1
  - distro=1.9.0
  - double-conversion=3.3.0
  - expat=2.6.2
  - farama-notifications=0.0.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozenlist=1.4.0
  - graphite2=1.3.14
  - greenlet=3.0.1
  - gymnasium=0.29.1
  - h11=0.14.0
  - harfbuzz=9.0.0
  - httpcore=1.0.2
  - httpx=0.26.0
  - icu=75.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jax-jumpy=1.0.0
  - jsonpatch=1.33
  - jsonpointer=2.1
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - langchain=0.2.12
  - langchain-community=0.2.11
  - langchain-core=0.2.29
  - langchain-openai=0.1.21
  - langchain-text-splitters=0.2.2
  - langsmith=0.1.98
  - lcms2=2.16
  - lerc=4.0.0
  - libavif16=1.1.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=18.1.8
  - libdeflate=1.21
  - libexpat=2.6.2
  - libffi=3.4.4
  - libflac=1.4.3
  - libglib=2.80.3
  - libiconv=1.17
  - libintl=0.22.5
  - libjpeg-turbo=3.0.3
  - libmad=0.15.1b
  - libogg=1.3.5
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libtiff=4.6.0
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzlib=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpg123=1.32.6
  - msys2-conda-epoch=20160418
  - multidict=6.0.4
  - mypy_extensions=1.0.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orjson=3.9.15
  - packaging=24.1
  - pcre2=10.44
  - pillow=10.4.0
  - pip=24.0
  - pixman=0.43.4
  - portmidi=2.0.4
  - pthread-stubs=0.3
  - pygame=2.6.0
  - pyparsing=3.0.9
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0post0
  - python_abi=3.12
  - pyyaml=6.0.1
  - qhull=2020.2
  - qt6-main=6.7.2
  - rav1e=0.6.6
  - regex=2024.7.24
  - requests=2.32.3
  - sdl2=2.30.5
  - sdl2_image=2.8.2
  - sdl2_mixer=2.6.3
  - sdl2_ttf=2.22.0
  - setuptools=72.1.0
  - six=1.16.0
  - sniffio=1.3.0
  - sqlalchemy=2.0.30
  - svt-av1=2.1.2
  - tbb=2021.8.0
  - tenacity=8.2.3
  - tiktoken=0.7.0
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.66.4
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - typing_inspect=0.9.0
  - tzdata=2024a
  - ucrt=10.0.20348.0
  - unicodedata2=15.1.0
  - urllib3=2.2.2
  - vc=14.2
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.9.3
  - zlib=1.3.1
  - zstd=1.5.6
  - pip:
      - dataclasses-json==0.6.7
      - jiter==0.5.0
      - marshmallow==3.21.3
      - openai==1.40.8
      - pydantic==2.8.2
      - pydantic-core==2.20.1
